export enum constants {
  HEADER_PICTURE = 'HEADER_PICTURE',
  CARD_PICTURE = 'CARD_PICTURE',
  MAIN_MODAL_PICTURE = 'MAIN_MODAL_PICTURE',
  CHARS_MODAL_PICTURE = 'CHARS_MODAL_PICTURE',
  FOOTER_LOGO = 'FOOTER_LOGO'
}

export const regExps = {
  getDigital: /[^0-9\']+/g
}