export const actionsTypes = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_CHARACTERS_SUCSESS: 'GET_CHARACTERS_SUCSESS',
  GET_NEXT_CHARACTERS: 'GET_NEXT_CHARACTERS',
  GET_NEXT_CHARACTERS_SUCSESS: 'GET_NEXT_CHARACTERS_SUCSESS',
  CHANGE_THEME: 'CHANGE_THEME',
  CALL_MODAL: 'CALL_MODAL',
  GET_ADDITIONAL: 'GET_ADDITIONAL',
  SET_EPISODE_CHARACTERS: 'SET_EPISODE_CHARACTERS',
  SET_CHARACTERS_FROM_LOCATION: 'SET_CHARACTERS_FROM_LOCATION',
  AUTHENTIFICATION_SIGN_UP: 'AUTHENTIFICATION_SIGN_UP',
  AUTHENTIFICATION_SIGN_UP_SUCCESS: 'AUTHENTIFICATION_SIGN_UP_SUCCESS',
  AUTHENTIFICATION_SIGN_UP_ERROR: 'AUTHENTIFICATION_SIGN_UP_ERROR',
  AUTHENTIFICATION_IDENTIFY: 'AUTHENTIFICATION_IDENTIFY',

  AUTHENTIFICATION_SIGN_IN: 'AUTHENTIFICATION_SIGN_IN',
  AUTHENTIFICATION_SIGN_IN_SUCCESS: 'AUTHENTIFICATION_SIGN_IN_SUCCESS',

  LOG_OUT_USER: 'LOG_OUT_USER',
  USER_LOAD_AVATAR: 'USER_LOAD_AVATAR',
};
