export const actionsTypes = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_CHARACTERS_SUCSESS: 'GET_CHARACTERS_SUCSESS',
  GET_NEXT_CHARACTERS: 'GET_NEXT_CHARACTERS',
  GET_NEXT_CHARACTERS_SUCSESS: 'GET_NEXT_CHARACTERS_SUCSESS',
  CHANGE_THEME: 'CHANGE_THEME',
  CALL_MODAL: 'CALL_MODAL',
  GET_ADDITIONAL: 'GET_ADDITIONAL',
  SET_EPISODE_CHARACTERS: 'SET_EPISODE_CHARACTERS',
  SET_CHARACTERS_FROM_LOCATION: 'SET_CHARACTERS_FROM_LOCATION',
};
