export const actionsTypes = {
  GET_CHARACTERS: 'GET_CHARACTERS',
  GET_CHARACTERS_SUCSESS: 'GET_CHARACTERS_SUCSESS',
  GET_NEXT_CHARACTERS: 'GET_NEXT_CHARACTERS',
  GET_NEXT_CHARACTERS_SUCSESS: 'GET_NEXT_CHARACTERS_SUCSESS',
  CHANGE_THEME: 'CHANGE_THEME',
};
