export const LOAD_HEROES = 'LOAD_HEROES'
export const LOAD_HEROES_SUCCESS = 'LOAD_HEROES_SUCCESS'
export const LOAD_HEROES_FAILURE = 'LOAD_HEROES_FAILURE'
export const LOAD_HEROES_LOADING = 'LOAD_HEROES_LOADING'