export const helper = {
  randomGif: () => {
    const colors = [
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/1.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/2.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/3.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/4.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/5.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/6.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/7.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/8.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/9.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/10.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/11.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/12.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/13.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/14.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/15.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/16.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/17.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/18.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/19.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/20.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/21.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/23.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/24.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/25.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/26.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/27.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/28.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/29.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/30.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/31.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/32.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/33.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/34.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/35.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/36.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/37.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/38.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/39.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/40.gif',
      '/Users/mac-pro-15/Desktop/MyNative/review/src/assets/gifs/41.gif',
    ];
    return colors[Math.floor(Math.random() * colors.length)];
  },
};
