export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_FAILED = "GET_CHARACTERS_FAILED";
export const GET_EPISODE = "GET_EPISODE"
export const GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS";
export const GET_EPISODE_FAILD = "GET_EPISODE_FAILD"