export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_FAILED = "GET_CHARACTERS_FAILED";

export const GET_EPISODE = "GET_EPISODE";
export const GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS";
export const GET_EPISODE_FAILED = "GET_EPISODE_FAILD";
export const GET_CHARACTER_BY_ID = "GET_CHARACTER_BY_ID";
export const GET_CHARACTER_BY_ID_SUCCESS = "GET_CHARACTER_BY_ID_SUCCESS";
export const GET_CHARACTER_BY_ID_FAILED = "GET_CHARACTER_BY_ID_FAILED";

export const SET_CHARACTER = 'SET_CHARACTER';
export const SET_EPISODE = 'SET_EPISODE'