export const GET_CHARACTERS = "GET_CHARACTERS",
    GET_CHARACTERS_BY_PAGE = "GET_CHARACTERS_BY_PAGE",
    GET_CHARACTERS_BY_PAGE_SUCCESS = "GET_CHARACTERS_BY_PAGE_SUCCESS",
    GET_CHARACTERS_BY_PAGE_AND_NAME = "GET_CHARACTERS_BY_PAGE_AND_NAME",
    GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS",
    GET_CHARACTERS_FAILED = "GET_CHARACTERS_FAILED";

export const GET_EPISODE = "GET_EPISODE",
    GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS",
    GET_EPISODE_FAILED = "GET_EPISODE_FAILED",
    GET_CHARACTER_BY_ID = "GET_CHARACTER_BY_ID",
    GET_CHARACTER_BY_ID_SUCCESS = "GET_CHARACTER_BY_ID_SUCCESS",
    GET_CHARACTER_BY_ID_FAILED = "GET_CHARACTER_BY_ID_FAILED",
    GET_CHARACTERS_PAGES_INFO = "GET_CHARACTERS_PAGES_INFO",
    CLEAR_CHARACTERS = "CLEAR_CHARACTERS";

export const SET_CHARACTER = 'SET_CHARACTER',
    SET_EPISODE = 'SET_EPISODE';

export const SIGN_IN_WITH_EMAIL_AND_PASSWORD = "SIGN_IN_WITH_EMAIL_AND_PASSWORD",
    SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS = "SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS",
    SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILED = "SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILED";

export const SIGN_UP = "SIGN_UP",
    SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS",
    SIGN_UP_FAILED = "SIGN_UP_FAILED";

export const SIGN_OUT = "SIGN_OUT";
